// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Flight flight
//
// swagger:model flight
type Flight struct {

	// from
	// Max Length: 3
	// Min Length: 3
	From string `json:"from,omitempty"`

	// to
	// Max Length: 3
	// Min Length: 3
	To string `json:"to,omitempty"`
}

// Validate validates this flight
func (m *Flight) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Flight) validateFrom(formats strfmt.Registry) error {
	if swag.IsZero(m.From) { // not required
		return nil
	}

	if err := validate.MinLength("from", "body", m.From, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("from", "body", m.From, 3); err != nil {
		return err
	}

	return nil
}

func (m *Flight) validateTo(formats strfmt.Registry) error {
	if swag.IsZero(m.To) { // not required
		return nil
	}

	if err := validate.MinLength("to", "body", m.To, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("to", "body", m.To, 3); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this flight based on context it is used
func (m *Flight) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Flight) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Flight) UnmarshalBinary(b []byte) error {
	var res Flight
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
