// Code generated by go-swagger; DO NOT EDIT.

package rest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PathResponse path response
//
// swagger:model PathResponse
type PathResponse struct {

	// path
	Path *Flight `json:"path,omitempty"`
}

// Validate validates this path response
func (m *PathResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePath(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PathResponse) validatePath(formats strfmt.Registry) error {
	if swag.IsZero(m.Path) { // not required
		return nil
	}

	if m.Path != nil {
		if err := m.Path.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("path")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("path")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this path response based on the context it is used
func (m *PathResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePath(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PathResponse) contextValidatePath(ctx context.Context, formats strfmt.Registry) error {

	if m.Path != nil {
		if err := m.Path.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("path")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("path")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PathResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PathResponse) UnmarshalBinary(b []byte) error {
	var res PathResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
