// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPathHandlerFunc turns a function with the right signature into a get path handler
type GetPathHandlerFunc func(GetPathParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPathHandlerFunc) Handle(params GetPathParams) middleware.Responder {
	return fn(params)
}

// GetPathHandler interface for that can handle valid get path params
type GetPathHandler interface {
	Handle(GetPathParams) middleware.Responder
}

// NewGetPath creates a new http.Handler for the get path operation
func NewGetPath(ctx *middleware.Context, handler GetPathHandler) *GetPath {
	return &GetPath{Context: ctx, Handler: handler}
}

/* GetPath swagger:route GET /path getPath

Get flight path

*/
type GetPath struct {
	Context *middleware.Context
	Handler GetPathHandler
}

func (o *GetPath) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPathParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
