// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"server/pkg/models/rest"
)

// GetPathOKCode is the HTTP code returned for type GetPathOK
const GetPathOKCode int = 200

/*GetPathOK User created

swagger:response getPathOK
*/
type GetPathOK struct {

	/*
	  In: Body
	*/
	Payload *rest.PathResponse `json:"body,omitempty"`
}

// NewGetPathOK creates GetPathOK with default headers values
func NewGetPathOK() *GetPathOK {

	return &GetPathOK{}
}

// WithPayload adds the payload to the get path o k response
func (o *GetPathOK) WithPayload(payload *rest.PathResponse) *GetPathOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get path o k response
func (o *GetPathOK) SetPayload(payload *rest.PathResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPathOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPathBadRequestCode is the HTTP code returned for type GetPathBadRequest
const GetPathBadRequestCode int = 400

/*GetPathBadRequest Path is not linked

swagger:response getPathBadRequest
*/
type GetPathBadRequest struct {

	/*
	  In: Body
	*/
	Payload *rest.Error `json:"body,omitempty"`
}

// NewGetPathBadRequest creates GetPathBadRequest with default headers values
func NewGetPathBadRequest() *GetPathBadRequest {

	return &GetPathBadRequest{}
}

// WithPayload adds the payload to the get path bad request response
func (o *GetPathBadRequest) WithPayload(payload *rest.Error) *GetPathBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get path bad request response
func (o *GetPathBadRequest) SetPayload(payload *rest.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPathBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPathDefault Internal server error

swagger:response getPathDefault
*/
type GetPathDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *rest.Error `json:"body,omitempty"`
}

// NewGetPathDefault creates GetPathDefault with default headers values
func NewGetPathDefault(code int) *GetPathDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPathDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get path default response
func (o *GetPathDefault) WithStatusCode(code int) *GetPathDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get path default response
func (o *GetPathDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get path default response
func (o *GetPathDefault) WithPayload(payload *rest.Error) *GetPathDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get path default response
func (o *GetPathDefault) SetPayload(payload *rest.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPathDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
