// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Flight path API
//
//  #### API for flights management"
//
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /api/v1
//  Version: 1.0.0
//  Contact: <krinitsinv@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
