// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "#### API for flights management\"\n",
    "title": "Flight path API",
    "contact": {
      "email": "krinitsinv@gmail.com"
    },
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "paths": {
    "/path": {
      "get": {
        "description": "Get flight path",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PathRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User created",
            "schema": {
              "$ref": "#/definitions/PathResponse"
            }
          },
          "400": {
            "description": "Path is not linked",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "$ref": "#/responses/InternalServerErrorResponse"
          }
        }
      }
    }
  },
  "definitions": {
    "PathRequest": {
      "type": "object",
      "required": [
        "flights"
      ],
      "properties": {
        "flights": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/flight"
          }
        }
      }
    },
    "PathResponse": {
      "type": "object",
      "properties": {
        "path": {
          "$ref": "#/definitions/flight"
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "flight": {
      "type": "object",
      "properties": {
        "from": {
          "type": "string",
          "maxLength": 3,
          "minLength": 3
        },
        "to": {
          "type": "string",
          "maxLength": 3,
          "minLength": 3
        }
      }
    }
  },
  "responses": {
    "InternalServerErrorResponse": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/error"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "#### API for flights management\"\n",
    "title": "Flight path API",
    "contact": {
      "email": "krinitsinv@gmail.com"
    },
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/api/v1",
  "paths": {
    "/path": {
      "get": {
        "description": "Get flight path",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PathRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User created",
            "schema": {
              "$ref": "#/definitions/PathResponse"
            }
          },
          "400": {
            "description": "Path is not linked",
            "schema": {
              "$ref": "#/definitions/error"
            }
          },
          "default": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "PathRequest": {
      "type": "object",
      "required": [
        "flights"
      ],
      "properties": {
        "flights": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/flight"
          }
        }
      }
    },
    "PathResponse": {
      "type": "object",
      "properties": {
        "path": {
          "$ref": "#/definitions/flight"
        }
      }
    },
    "error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "flight": {
      "type": "object",
      "properties": {
        "from": {
          "type": "string",
          "maxLength": 3,
          "minLength": 3
        },
        "to": {
          "type": "string",
          "maxLength": 3,
          "minLength": 3
        }
      }
    }
  },
  "responses": {
    "InternalServerErrorResponse": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/error"
      }
    }
  }
}`))
}
